"""initial_schema

Revision ID: f8f439d869bb
Revises: 
Create Date: 2026-03-26 00:02:53.698121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8f439d869bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('area_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_table('ng_relations',
    sa.Column('ng_relation_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Enum('TEACHER', 'STUDENT', name='ng_created_by'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ng_relation_id'),
    sa.UniqueConstraint('teacher_id', 'student_id', name='uq_ng_relations')
    )
    op.create_index(op.f('ix_ng_relations_student_id'), 'ng_relations', ['student_id'], unique=False)
    op.create_index(op.f('ix_ng_relations_teacher_id'), 'ng_relations', ['teacher_id'], unique=False)
    op.create_table('subjects',
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('subject_name', sa.String(length=50), nullable=False),
    sa.Column('grade_category', sa.Enum('ELEMENTARY', 'JUNIOR_HIGH', 'HIGH_SCHOOL', name='grade_category'), nullable=False),
    sa.Column('subject_category', sa.Enum('ENGLISH', 'MATH', 'JAPANESE', 'SCIENCE', 'SOCIAL', name='subject_category'), nullable=False),
    sa.Column('is_jhs_exam_target', sa.Boolean(), nullable=False),
    sa.Column('is_hs_exam_target', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('CLASSROOM_MANAGER', 'AREA_MANAGER', 'SYSTEM_ADMIN', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('login_failed_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.Column('classroom_code', sa.String(length=20), nullable=False),
    sa.Column('classroom_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('OPERATING', 'CLOSED', name='classroom_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    op.create_index(op.f('ix_classrooms_area_id'), 'classrooms', ['area_id'], unique=False)
    op.create_index(op.f('ix_classrooms_classroom_code'), 'classrooms', ['classroom_code'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('refresh_token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_info', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('refresh_token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_areas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('area_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.area_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'area_id')
    )
    op.create_table('classroom_settings',
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('booth_count', sa.Integer(), nullable=False),
    sa.Column('weekday_slots', sa.Integer(), nullable=False),
    sa.Column('saturday_slots', sa.Integer(), nullable=False),
    sa.Column('operating_days', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('classroom_id')
    )
    op.create_table('google_form_connections',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('data_type', sa.Enum('TEACHER_SHIFT', 'STUDENT_PREFERENCE', name='google_form_data_type'), nullable=False),
    sa.Column('spreadsheet_url', sa.String(length=500), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('oauth_token_encrypted', sa.Text(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.Enum('FULFILLMENT_LOW', 'UNANSWERED_PREFERENCE', 'TERM_DEADLINE', 'SCHEDULE_CONFLICT', name='notification_type'), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'WARNING', 'INFO', name='severity'), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('policy_templates',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('policies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('students',
    sa.Column('student_version_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_reason_type', sa.Enum('COURSE_CHANGE', 'GRADE_UP', 'PREFERENCE_CHANGE', 'GOAL_CHANGE', 'STATUS_CHANGE', 'INITIAL', 'OTHER', name='student_change_reason'), nullable=False),
    sa.Column('change_reason_note', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade', sa.Enum('ELE1', 'ELE2', 'ELE3', 'ELE4', 'ELE5', 'ELE6', 'JHS1', 'JHS2', 'JHS3', 'HS1', 'HS2', 'HS3', name='grade'), nullable=False),
    sa.Column('max_consecutive_slots', sa.Integer(), nullable=False),
    sa.Column('preferred_teacher_id', sa.String(length=20), nullable=True),
    sa.Column('preferred_teacher_gender', sa.Enum('MALE', 'FEMALE', 'ANY', name='preferred_gender'), nullable=True),
    sa.Column('aspiration_level', sa.Enum('A', 'B', 'C', name='aspiration_level'), nullable=True),
    sa.Column('enrollment_purpose', sa.Enum('HS_EXAM', 'JHS_EXAM', 'INTERNAL', 'REMEDIAL', 'OTHER', name='enrollment_purpose'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='student_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_consecutive_slots BETWEEN 1 AND 4', name='chk_students_consecutive'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('student_version_id'),
    sa.UniqueConstraint('student_id', 'classroom_id', 'version_number', name='uq_students_version')
    )
    op.create_index(op.f('ix_students_classroom_id'), 'students', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_table('teachers',
    sa.Column('teacher_version_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_reason_type', sa.Enum('SCHEDULE_CHANGE', 'SUBJECT_CHANGE', 'GRADE_CHANGE', 'NG_CHANGE', 'STATUS_CHANGE', 'INITIAL', 'OTHER', name='teacher_change_reason'), nullable=False),
    sa.Column('change_reason_note', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender'), nullable=False),
    sa.Column('min_slots_per_week', sa.Integer(), nullable=False),
    sa.Column('max_slots_per_week', sa.Integer(), nullable=False),
    sa.Column('max_consecutive_slots', sa.Integer(), nullable=False),
    sa.Column('has_jhs_exam_experience', sa.Boolean(), nullable=False),
    sa.Column('has_hs_exam_experience', sa.Boolean(), nullable=False),
    sa.Column('university_rank', sa.Enum('A', 'B', 'C', name='university_rank'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='teacher_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('max_consecutive_slots BETWEEN 1 AND 4', name='chk_teachers_consecutive'),
    sa.CheckConstraint('min_slots_per_week <= max_slots_per_week', name='chk_teachers_slots'),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('teacher_version_id'),
    sa.UniqueConstraint('teacher_id', 'classroom_id', 'version_number', name='uq_teachers_version')
    )
    op.create_index(op.f('ix_teachers_classroom_id'), 'teachers', ['classroom_id'], unique=False)
    op.create_index(op.f('ix_teachers_teacher_id'), 'teachers', ['teacher_id'], unique=False)
    op.create_table('terms',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('term_name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'CONFIRMED', 'ARCHIVED', name='term_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('term_id')
    )
    op.create_index(op.f('ix_terms_classroom_id'), 'terms', ['classroom_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('time_slot_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('day_type', sa.Enum('WEEKDAY', 'SATURDAY', name='day_type'), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.PrimaryKeyConstraint('time_slot_id'),
    sa.UniqueConstraint('classroom_id', 'day_type', 'slot_number', name='uq_time_slots')
    )
    op.create_table('user_classrooms',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'classroom_id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('policy_type', sa.Enum('P001', 'P002', 'P003', 'P004', 'P005', 'P006', name='policy_type'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('term_id', 'policy_type', name='uq_policies')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', 'ARCHIVED', name='schedule_status'), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('master_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fulfillment_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('soft_constraint_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fulfillment_rate IS NULL OR (fulfillment_rate >= 0 AND fulfillment_rate <= 100)', name='chk_schedules_fulfillment'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['parent_version_id'], ['schedules.schedule_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedules_term_id'), 'schedules', ['term_id'], unique=False)
    op.create_table('student_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', name='day_of_week'), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('preference_value', sa.Enum('PREFERRED', 'UNAVAILABLE', 'POSSIBLE', name='student_preference_value'), nullable=False),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('student_id', 'term_id', 'day_of_week', 'slot_number', name='uq_student_prefs')
    )
    op.create_index(op.f('ix_student_preferences_student_id'), 'student_preferences', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_preferences_term_id'), 'student_preferences', ['term_id'], unique=False)
    op.create_table('student_subjects',
    sa.Column('student_version_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('slots_per_week', sa.Integer(), nullable=False),
    sa.CheckConstraint('slots_per_week >= 1', name='chk_student_subjects_slots'),
    sa.ForeignKeyConstraint(['student_version_id'], ['students.student_version_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('student_version_id', 'subject_id')
    )
    op.create_table('teacher_grades',
    sa.Column('teacher_version_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Enum('ELE1', 'ELE2', 'ELE3', 'ELE4', 'ELE5', 'ELE6', 'JHS1', 'JHS2', 'JHS3', 'HS1', 'HS2', 'HS3', name='grade'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_version_id'], ['teachers.teacher_version_id'], ),
    sa.PrimaryKeyConstraint('teacher_version_id', 'grade')
    )
    op.create_table('teacher_shift_preferences',
    sa.Column('preference_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('classroom_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', name='day_of_week'), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('preference_value', sa.Enum('AVAILABLE', 'UNAVAILABLE', name='teacher_preference_value'), nullable=False),
    sa.Column('is_manually_edited', sa.Boolean(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.classroom_id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('preference_id'),
    sa.UniqueConstraint('teacher_id', 'term_id', 'day_of_week', 'slot_number', name='uq_teacher_shift_prefs')
    )
    op.create_index(op.f('ix_teacher_shift_preferences_teacher_id'), 'teacher_shift_preferences', ['teacher_id'], unique=False)
    op.create_index(op.f('ix_teacher_shift_preferences_term_id'), 'teacher_shift_preferences', ['term_id'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('teacher_version_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_version_id'], ['teachers.teacher_version_id'], ),
    sa.PrimaryKeyConstraint('teacher_version_id', 'subject_id')
    )
    op.create_table('term_constraints',
    sa.Column('constraint_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('TEACHER', 'STUDENT', 'CLASSROOM', name='constraint_target_type'), nullable=False),
    sa.Column('target_id', sa.String(length=50), nullable=False),
    sa.Column('constraint_type', sa.Enum('MAX_SLOTS', 'MIN_SLOTS', 'MAX_CONSECUTIVE', 'SUBJECT_LIMIT', 'DAY_LIMIT', 'PREFERRED_TEACHER', 'NG_TEACHER', 'GENDER_PREFERENCE', 'BOOTH_CAPACITY', name='constraint_type'), nullable=False),
    sa.Column('constraint_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.term_id'], ),
    sa.PrimaryKeyConstraint('constraint_id')
    )
    op.create_index(op.f('ix_term_constraints_term_id'), 'term_constraints', ['term_id'], unique=False)
    op.create_table('schedule_slots',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', name='day_of_week'), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('booth_number', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.String(length=20), nullable=False),
    sa.Column('student1_id', sa.String(length=20), nullable=False),
    sa.Column('student2_id', sa.String(length=20), nullable=True),
    sa.Column('subject_id', sa.String(length=20), nullable=False),
    sa.Column('slot_type', sa.Enum('ONE_TO_TWO', 'ONE_TO_ONE', name='slot_type'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ABSENT', 'SUBSTITUTED', name='slot_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_index(op.f('ix_schedule_slots_schedule_id'), 'schedule_slots', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_slots_student1_id'), 'schedule_slots', ['student1_id'], unique=False)
    op.create_index(op.f('ix_schedule_slots_teacher_id'), 'schedule_slots', ['teacher_id'], unique=False)
    op.create_table('absences',
    sa.Column('absence_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('absent_type', sa.Enum('TEACHER', 'STUDENT', name='absent_type'), nullable=False),
    sa.Column('absent_person_id', sa.String(length=20), nullable=False),
    sa.Column('absence_reason', sa.String(length=200), nullable=True),
    sa.Column('needs_substitution', sa.Boolean(), nullable=False),
    sa.Column('substitution_status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='substitution_status'), nullable=False),
    sa.Column('registered_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['schedule_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('absence_id')
    )
    op.create_index(op.f('ix_absences_slot_id'), 'absences', ['slot_id'], unique=False)
    op.create_table('substitutions',
    sa.Column('substitution_id', sa.UUID(), nullable=False),
    sa.Column('absence_id', sa.UUID(), nullable=False),
    sa.Column('original_slot_id', sa.UUID(), nullable=False),
    sa.Column('new_slot_id', sa.UUID(), nullable=False),
    sa.Column('substitution_type', sa.Enum('RESCHEDULE', 'SUBSTITUTE', name='substitution_type'), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['absence_id'], ['absences.absence_id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['new_slot_id'], ['schedule_slots.slot_id'], ),
    sa.ForeignKeyConstraint(['original_slot_id'], ['schedule_slots.slot_id'], ),
    sa.PrimaryKeyConstraint('substitution_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('substitutions')
    op.drop_index(op.f('ix_absences_slot_id'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_schedule_slots_teacher_id'), table_name='schedule_slots')
    op.drop_index(op.f('ix_schedule_slots_student1_id'), table_name='schedule_slots')
    op.drop_index(op.f('ix_schedule_slots_schedule_id'), table_name='schedule_slots')
    op.drop_table('schedule_slots')
    op.drop_index(op.f('ix_term_constraints_term_id'), table_name='term_constraints')
    op.drop_table('term_constraints')
    op.drop_table('teacher_subjects')
    op.drop_index(op.f('ix_teacher_shift_preferences_term_id'), table_name='teacher_shift_preferences')
    op.drop_index(op.f('ix_teacher_shift_preferences_teacher_id'), table_name='teacher_shift_preferences')
    op.drop_table('teacher_shift_preferences')
    op.drop_table('teacher_grades')
    op.drop_table('student_subjects')
    op.drop_index(op.f('ix_student_preferences_term_id'), table_name='student_preferences')
    op.drop_index(op.f('ix_student_preferences_student_id'), table_name='student_preferences')
    op.drop_table('student_preferences')
    op.drop_index(op.f('ix_schedules_term_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('policies')
    op.drop_table('user_classrooms')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_terms_classroom_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_teachers_teacher_id'), table_name='teachers')
    op.drop_index(op.f('ix_teachers_classroom_id'), table_name='teachers')
    op.drop_table('teachers')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_classroom_id'), table_name='students')
    op.drop_table('students')
    op.drop_table('policy_templates')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('google_form_connections')
    op.drop_table('classroom_settings')
    op.drop_table('user_areas')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_classrooms_classroom_code'), table_name='classrooms')
    op.drop_index(op.f('ix_classrooms_area_id'), table_name='classrooms')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_ng_relations_teacher_id'), table_name='ng_relations')
    op.drop_index(op.f('ix_ng_relations_student_id'), table_name='ng_relations')
    op.drop_table('ng_relations')
    op.drop_table('areas')
    # ### end Alembic commands ###
